**Importations des dépendances**

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

**Collecte et analyse des données**

In [3]:
vaches_dataset = pd.read_csv('data/cattle_dataset.csv')

vaches_dataset.head()

body_temperature  walking_capacity  heart_rate health_status
0              38.2             12432          50     unhealthy
1              38.9             11987          62       healthy
2              38.6             13121          71       healthy
3              39.5             12055          68     unhealthy
4              39.7             10352          63       healthy

In [4]:
vaches_dataset.shape

(178, 4)

In [5]:
vaches_dataset.describe()

body_temperature  walking_capacity  heart_rate
count        178.000000        178.000000  178.000000
mean          39.011236       9303.179775   53.955056
std            0.872225       3237.390592   13.157808
min           35.500000       5004.000000   37.000000
25%           38.300000       6019.000000   42.000000
50%           38.900000      11203.000000   50.000000
75%           39.700000      12291.000000   63.000000
max           40.600000      13257.000000   83.000000

In [6]:
vaches_dataset['health_status'].value_counts()

health_status
healthy      90
unhealthy    88
Name: count, dtype: int64

In [7]:
vaches_dataset.groupby('health_status').mean()

body_temperature  walking_capacity  heart_rate
health_status                                                
healthy               38.268889      12285.666667   64.133333
unhealthy             39.770455       6252.909091   43.545455

In [8]:
X = vaches_dataset.drop('health_status', axis=1)  # Toutes les colonnes sauf 'health_status'
Y = vaches_dataset['health_status']

**Normalisation des données**

In [9]:
scaler = StandardScaler()
scaler.fit(X)
standardized_data = scaler.transform(X)
print(standardized_data)

[[-9.32699777e-01  9.69189896e-01 -3.01434168e-01]
 [-1.27890967e-01  8.31345766e-01  6.13144501e-01]
 [-4.72809028e-01  1.18261598e+00  1.29907850e+00]
 [ 5.61945157e-01  8.52409588e-01  1.07043384e+00]
 [ 7.91890531e-01  3.24884746e-01  6.89359390e-01]
 [ 1.13680859e+00  1.51226549e-02  4.60714723e-01]
 [-8.17727090e-01  8.19265044e-01  1.55855167e-01]
 [-1.16264515e+00  9.14362006e-01 -3.77649057e-01]
 [-1.04767246e+00  1.22474362e+00 -1.49004390e-01]
 [-9.32699777e-01  1.15442763e+00  1.55855167e-01]
 [-8.17727090e-01  1.00914921e+00  6.89359390e-01]
 [-7.02754403e-01  9.25513441e-01 -3.01434168e-01]
 [-5.87781716e-01  8.55507209e-01  1.68015295e+00]
 [-9.32699777e-01  7.28504751e-01 -1.49004390e-01]
 [-1.16264515e+00  8.88341990e-01  1.68015295e+00]
 [-8.17727090e-01  9.70738707e-01  3.84499834e-01]
 [-5.87781716e-01  1.19345765e+00  1.29907850e+00]
 [-9.32699777e-01  1.03919613e+00 -7.27895008e-02]
 [-5.87781716e-01  7.83332641e-01  1.07043384e+00]
 [-1.16264515e+00  5.77340851e-

**Entrainement - Test - Découpage**

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(standardized_data, Y, test_size=0.2, stratify=Y, random_state=42)

In [11]:
print(X.shape, X_train.shape, X_test.shape)

(178, 3) (142, 3) (36, 3)


**Entraînement du modèle**

In [12]:
classifier = svm.SVC(kernel='rbf')
classifier.fit(X_train, Y_train)

SVC()

**Evaluation du modèle**

In [13]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.9859154929577465


In [14]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.9444444444444444


**Mise en place d'un système de prédiction**

In [17]:
input_data = (38.2,12658,53)

input_data_as_numpy_array = np.asarray(input_data)

input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

# if prediction[0] == 0:
#   print('La vache est en bonne santé')
# else:
#   print('La vache est malade')

[[-0.93269978  1.03919613 -0.0727895 ]]
['healthy']


c:\Users\DPcomputer\Desktop\P_DOC\PYTHON\APP\Smart_Cattle\IA\.venv\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


**Sauvegarde du modèle**

In [20]:
import joblib
# Supposons que classifier est votre modèle
joblib.dump(classifier, 'models/model.pkl')
joblib.dump(scaler, 'models/scaler.pkl')  # Si vous utilisez un scaler


['models/scaler.pkl']